artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/refs/heads/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzipped_data_dir: artifacts/data_ingestion